import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import LayoutClient from "@/components/layout/Layout";
import { getServerSession } from "next-auth";
import { NEXT_AUTH_CONFIG } from "@/lib/auth";

export const metadata: Metadata = {
  title: "DEV",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(NEXT_AUTH_CONFIG);

  return (
    <html lang="en">
      <body className="bg-[#030711] text-[#D1D5DB]">
        <div className="min-h-screen flex  flex-col">
          <Providers>
            <LayoutClient session={session}>{children}</LayoutClient>
          </Providers>
        </div>
      </body>
    </html>
  );
}
